### PR TITLE
Bearer

### PR DESCRIPTION
**Pull request by drekle**
From https://github.com/bitly/oauth2_proxy/pull/470

### CODE REVIEW

**Comment by drekle** [comment]
@josdotso @dcwangmit01 @rtluckie please approve

**Review by ghost — APPROVED** [review]
Approved, but @dcwangmit01 knows a lot of about oauth2-proxy, so will leave open for this review.

**Comment by darkyat** [comment]
@dcwangmit01 would be great to have this reviewed today. Thanks!

**Comment by dcwangmit01** [comment]
+1 👍 

This PR indeed matches that of the upstream PR.

@drekle When you create these PR's that are based off of upstream PRs, it would be best to git cherry-pick them in order to maintain history.  Right now history/lineage is getting clobbered because the commit ids are different.

**Comment by darkyat** [comment]
@dcwangmit01, do you want @drekle to change that or are you fine merging this time? We don't have write access to this organisation.

**Comment by dcwangmit01** [comment]
@darkyat and @drekle have now been invited to be members of this org.

**Comment by dcwangmit01** [comment]
I'm fine with it, just not ideal.

**Comment by drekle** [comment]
See Pull #4

**Pull request closed without merging**
