### PR TITLE
Oidc userinfo support

### PR DESCRIPTION
**Pull request by drekle**
From https://github.com/dcwangmit01/oauth2_proxy/tree/oidc_userinfo_support

### CODE REVIEW

**Comment by drekle** [comment]
@josdotso @dcwangmit01 @rtluckie please approve

**Review by ghost — APPROVED** [review]
Approved, but @dcwangmit01 knows a lot of about oauth2-proxy, so will leave open for this review.

**Comment by darkyat** [comment]
@dcwangmit01 would be great to have this reviewed today. Thanks!

**Comment by dcwangmit01** [comment]
+1 👍

**Comment by dcwangmit01** [comment]
Real link for the upstream PR, in case by some miracle it actually merges is:

https://github.com/bitly/oauth2_proxy/pull/481

**Comment by drekle** [comment]
See #5

**Pull request closed without merging**
